version: "3"
services:
    rabbitmq:
        container_name: rabbitmq
        image: "rabbitmq:management"
        restart: always
        volumes:
         - "./data:/var/lib/rabbitmq"
         - "./log:/var/log/rabbitmq/log"
        ports:
            - 15672:15672
            - 4369:4369
            - 5671:5671
            - 5672:5672
            - 25672:25672
            - 15671:15671